INSERT INTO genre_table (movie_id, genre_name, description) VALUES

(1, 'Action', 'High-energy movies with fights and chases'), 
(1, 'Adventure', 'Exciting journeys and explorations'),
(2, 'Action', 'High-energy movies with fights and chases'), 
(2, 'Adventure', 'Exciting journeys and explorations'),
(3, 'Action', 'High-energy movies with fights and chases'), 
(3, 'Thriller', 'Suspenseful and tense narratives'),
(4, 'Action', 'High-energy movies with fights and chases'), 
(4, 'Adventure', 'Exciting journeys and explorations'),
(5, 'Action', 'High-energy movies with fights and chases'), 
(6, 'Action', 'High-energy movies with fights and chases'),
(6, 'Drama', 'Emotional and character-driven stories'),
(7, 'Action', 'High-energy movies with fights and chases'), 
(7, 'Drama', 'Emotional and character-driven stories'),
(8, 'Fantasy', 'Magical and supernatural elements'), 
(8, 'Action', 'High-energy movies with fights and chases'),
(9, 'Drama', 'Emotional and character-driven stories'), 
(9, 'Romance', 'Love and relationships as main themes'),
(10, 'Comedy', 'Light-hearted and humorous movies'),
(10, 'Romance', 'Love and relationships as main themes'),
(11, 'Action', 'High-energy movies with fights and chases'), 
(11, 'Drama', 'Emotional and character-driven stories'),
(12, 'Action', 'High-energy movies with fights and chases'), 
(12, 'Comedy', 'Light-hearted and humorous movies'),
(13, 'Drama', 'Emotional and character-driven stories'), 
(14, 'Fantasy', 'Magical and supernatural elements'), 
(14, 'Action', 'High-energy movies with fights and chases'),
(15, 'Sports', 'Based on sports and competitions'), 
(15, 'Drama', 'Emotional and character-driven stories'),
(16, 'Action', 'High-energy movies with fights and chases'), 
(17, 'Action', 'High-energy movies with fights and chases'), 
(17, 'Comedy', 'Light-hearted and humorous movies'),
(18, 'Action', 'High-energy movies with fights and chases'),
(18, 'Comedy', 'Light-hearted and humorous movies'),
(19, 'Action', 'High-energy movies with fights and chases'), 
(19, 'Fantasy', 'Magical and supernatural elements'),
(20, 'Action', 'High-energy movies with fights and chases'), 
(20, 'Thriller', 'Suspenseful and tense narratives'),
(21, 'Action', 'High-energy movies with fights and chases'), 
(21, 'Sports', 'Based on sports and competitions'),
(22, 'Fantasy', 'Magical and supernatural elements'), 
(23, 'Action', 'High-energy movies with fights and chases'), 
(24, 'Action', 'High-energy movies with fights and chases'), 
(24, 'Comedy', 'Light-hearted and humorous movies'),
(25, 'Drama', 'Emotional and character-driven stories'),
(26, 'Action', 'High-energy movies with fights and chases'), 
(27, 'Action', 'High-energy movies with fights and chases'),
(28, 'Action', 'High-energy movies with fights and chases'),
(29, 'Action', 'High-energy movies with fights and chases'), 
(30, 'Thriller', 'Suspenseful and tense narratives'), 
(31, 'Drama', 'Emotional and character-driven stories'), 
(32, 'Action', 'High-energy movies with fights and chases'),
(33, 'Sports', 'Based on sports and competitions'),
(34, 'Action', 'High-energy movies with fights and chases'),
(35, 'Political', 'Politics and government themes'),
(36, 'Action', 'High-energy movies with fights and chases'),
(37, 'Sci-Fi', 'Science-based futuristic themes'), 
(38, 'Sci-Fi', 'Science-based futuristic themes'), 
(39, 'Thriller', 'Suspenseful and tense narratives'), 
(40, 'Drama', 'Emotional and character-driven stories'),
(41, 'Action', 'High-energy movies with fights and chases'), 
(42, 'Crime', 'Focus on criminals and law enforcement'),
(43, 'Drama', 'Emotional and character-driven stories'), 
(44, 'Crime', 'Focus on criminals and law enforcement'), 
(45, 'Thriller', 'Suspenseful and tense narratives'), 
(46, 'Action', 'High-energy movies with fights and chases'), 
(47, 'Action', 'High-energy movies with fights and chases'), 
(48, 'Drama', 'Emotional and character-driven stories'), 
(49, 'Crime', 'Focus on criminals and law enforcement'), 
(50, 'Sports', 'Based on sports and competitions'),
(51, 'Action', 'High-energy movies with fights and chases'), 
(52, 'Sci-Fi', 'Science-based futuristic themes'), 
(53, 'Sci-Fi', 'Science-based futuristic themes'), 
(54, 'Drama', 'Emotional and character-driven stories'),
(55, 'Crime', 'Focus on criminals and law enforcement'), 
(56, 'Crime', 'Focus on criminals and law enforcement'), 
(57, 'Sci-Fi', 'Science-based futuristic themes'), 
(58, 'Sci-Fi', 'Science-based futuristic themes'), 
(59, 'Sci-Fi', 'Science-based futuristic themes'), 
(60, 'Drama', 'Emotional and character-driven stories'), 
(61, 'Drama', 'Emotional and character-driven stories'), 
(62, 'Sci-Fi', 'Science-based futuristic themes'), 
(63, 'Thriller', 'Suspenseful and tense narratives'), 
(64, 'Thriller', 'Suspenseful and tense narratives'), 
(65, 'Crime', 'Focus on criminals and law enforcement'), 
(66, 'Sci-Fi', 'Science-based futuristic themes'),
(67, 'Sci-Fi', 'Science-based futuristic themes'),
(68, 'Action', 'High-energy movies with fights and chases'), 
(69, 'Action', 'High-energy movies with fights and chases'), 
(70, 'Action', 'High-energy movies with fights and chases'), 
(71, 'Fantasy', 'Magical and supernatural elements'), 
(72, 'Action', 'High-energy movies with fights and chases'), 
(73, 'Crime', 'Focus on criminals and law enforcement'),
(74, 'Drama', 'Emotional and character-driven stories'), 
(75, 'Comedy', 'Light-hearted and humorous movies'), 
(76, 'Comedy', 'Light-hearted and humorous movies'),
(76, 'Drama', 'Emotional and character-driven stories'),
(77, 'Drama', 'Emotional and character-driven stories'), 
(77, 'Sports', 'Based on sports and competitions'),
(78, 'Drama', 'Emotional and character-driven stories'), 
(78, 'Sports', 'Based on sports and competitions'),
(79, 'Drama', 'Emotional and character-driven stories'), 
(79, 'Family', 'Family-oriented themes and relationships'),
(80, 'Action', 'High-energy movies with fights and chases'), 
(80, 'Drama', 'Emotional and character-driven stories'),
(81, 'Drama', 'Emotional and character-driven stories'),
(81, 'Historical', 'Based on historical events and figures'),
(82, 'Drama', 'Emotional and character-driven stories'), 
(82, 'Romance', 'Love and relationships as main themes'),
(83, 'Drama', 'Emotional and character-driven stories'), 
(83, 'Adventure', 'Exciting journeys and explorations'),
(84, 'Action', 'High-energy movies with fights and chases'),
(84, 'Sports', 'Based on sports and competitions'),
(85, 'Comedy', 'Light-hearted and humorous movies'), 
(85, 'Action', 'High-energy movies with fights and chases'),
(86, 'Action', 'High-energy movies with fights and chases'), 
(86, 'Romance', 'Love and relationships as main themes'),
(87, 'Sci-Fi', 'Science-based futuristic themes'), 
(87, 'Fantasy', 'Magical and supernatural elements'),
(88, 'Comedy', 'Light-hearted and humorous movies'), 
(88, 'Drama', 'Emotional and character-driven stories'),
(89, 'Action', 'High-energy movies with fights and chases'), 
(89, 'Thriller', 'Suspenseful and tense narratives'),
(90, 'Drama', 'Emotional and character-driven stories'), 
(90, 'Musical', 'Strong focus on music and performance'),
(91, 'Crime', 'Focus on criminals and law enforcement'),
(92, 'Crime', 'Focus on criminals and law enforcement'), 
(92, 'Thriller', 'Suspenseful and tense narratives'),
(93, 'Action', 'High-energy movies with fights and chases'),
(93, 'Thriller', 'Suspenseful and tense narratives'),
(94, 'Action', 'High-energy movies with fights and chases'),
(94, 'Thriller', 'Suspenseful and tense narratives'),
(95, 'Drama', 'Emotional and character-driven stories'),
(95, 'Thriller', 'Suspenseful and tense narratives'),
(96, 'Drama', 'Emotional and character-driven stories'),
(96, 'Thriller', 'Suspenseful and tense narratives'),
(97, 'Crime', 'Focus on criminals and law enforcement'),
(97, 'Thriller', 'Suspenseful and tense narratives'),
(98, 'Crime', 'Focus on criminals and law enforcement'),
(98, 'Thriller', 'Suspenseful and tense narratives'),
(99, 'Thriller', 'Suspenseful and tense narratives'),
(99, 'Mystery', 'Focus on solving crimes and uncovering secrets'),
(100, 'Action', 'High-energy movies with fights and chases'),
(100, 'Thriller', 'Suspenseful and tense narratives');